/*
 * Test harness for scan_emoji_presentation().
 *
 * Test data is generated by emoji_test_data.pl and included into the
 * emoji_test_units[] array below. Each unit carries a pre-classified 
 * .categories array, so no runtime codepoint classification is needed here.
 *
 * Each test unit covers a single scanner token.  The scanner is called
 * once per unit and the returned (is_emoji, has_vs) pair is compared
 * against the expected values.  If the scanner does not consume all
 * .length categories the test also fails.
 *
 * Build:
 *   perl emoji_test_data.pl > emoji_test_data.h
 *   cc -o emoji_test emoji_test.c
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>

enum {
  EMOJI = 0,
  EMOJI_TEXT_PRESENTATION,
  EMOJI_EMOJI_PRESENTATION,
  EMOJI_MODIFIER_BASE_TEXT,
  EMOJI_MODIFIER_BASE_EMOJI,
  EMOJI_MODIFIER,
  EMOJI_VS_BASE,
  REGIONAL_INDICATOR,
  KEYCAP_BASE,
  COMBINING_ENCLOSING_KEYCAP,
  COMBINING_ENCLOSING_CIRCLE_BACKSLASH,
  ZWJ,
  VS15,
  VS16,
  TAG_BASE,
  TAG_SEQUENCE,
  TAG_TERM,
};

#define EMOJI_LINKAGE static
typedef unsigned char* emoji_text_iter_t;
#include "emoji_presentation_scanner.c"

#define MAX_SEQUENCE 16

typedef struct {
  const char* description;
  unsigned int sequence[MAX_SEQUENCE];
  unsigned char categories[MAX_SEQUENCE];
  unsigned int length;
  bool is_emoji;
  bool has_vs;
} emoji_test_unit_t;

static const emoji_test_unit_t emoji_test_units[] = {
  #include "emoji_test_data.h"
}; /* emoji_test_units[] */

static const size_t emoji_test_units_count =
    sizeof(emoji_test_units) / sizeof(emoji_test_units[0]);

static int tests_run = 0;
static int tests_passed = 0;
static int tests_failed = 0;

static void run_test(const emoji_test_unit_t* u) {
  unsigned char* p = (unsigned char*)u->categories;
  unsigned char* pe = p + u->length;

  bool is_emoji = false;
  bool has_vs = false;
  emoji_text_iter_t end = scan_emoji_presentation(p, pe, &is_emoji, &has_vs);

  bool ok = (end == pe) && (is_emoji == u->is_emoji) && (has_vs == u->has_vs);

  tests_run++;
  if (ok) {
    tests_passed++;
    printf("PASS  %s\n", u->description);
  } else {
    tests_failed++;
    printf("FAIL  %s\n", u->description);
    if (end != pe)
      printf("      consumed %td of %u categories\n", end - p, u->length);
    if (is_emoji != u->is_emoji)
      printf("      is_emoji: got %s, expected %s\n", 
             is_emoji ? "true" : "false", u->is_emoji ? "true" : "false");
    if (has_vs != u->has_vs)
      printf("      has_vs:   got %s, expected %s\n", 
             has_vs ? "true" : "false", u->has_vs ? "true" : "false");
  }
}

int main(void) {
  for (size_t i = 0; i < emoji_test_units_count; i++)
    run_test(&emoji_test_units[i]);

  printf("\n========================================\n");
  printf("Total:  %d\n", tests_run);
  printf("Passed: %d\n", tests_passed);
  printf("Failed: %d\n", tests_failed);
  printf("========================================\n");

  return tests_failed > 0 ? 1 : 0;
}
